version: '3.9'

services:

  api:

    build: .

    ports:

      - 3000:3000

    volumes:

      - .:/shares/src/app

    environment:

      PORT: 3000

      MONGODB_URI: 'mongodb+srv://xt_social:xt_social123@cluster0.2w6mj.mongodb.net/applauds?retryWrites=true&w=majority'