version: "3.9"

services:
  #MongoDB services
  mongo_db:
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - mongo_db:/data/db

  #Rabbitmq services
  rabbitmq:
    image: rabbitmq:management
    ports:
      - 15672:15672
      - 15671:15671
      - 5672:5672
    volumes:
      - ./rabbitmq/lib:/var/lib/rabbitmq

  # Wait for a bit
  waitforrabbit:
    image: dadarek/wait-for-dependencies
    depends_on:
      - rabbitmq
    command: rabbitmq:5672
  #Node users API service
  users:
    build:
      context: ./users
      dockerfile: Dockerfile
    container_name: users
    restart: always
    ports:
      - 8001:8001
    volumes:
      - ./users:/users/src/app/
    env_file: users/.env.dev
    depends_on:
      - waitforrabbit
      - mongo_db
      - rabbitmq

  #Node posts API service
  posts:
    build:
      context: ./posts
      dockerfile: Dockerfile
    container_name: posts
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./posts:/posts/src/app/
    env_file: posts/.env.dev
    depends_on:
      - waitforrabbit
      - mongo_db
      - rabbitmq

  #Node shares API service
  shares:
    build:
      context: ./shares
      dockerfile: Dockerfile
    container_name: shares
    restart: always
    ports:
      - 8002:8002
    volumes:
      - ./shares:/shares/src/app
    environment:
      APP_SECRET: "barkat"
      MONGODB_URI: "mongodb://mongo_db:27017/shares"
      PORT: 8002
      MOJO_API_KEY: "test-39c833cd-adc0-4787-8027-400b8551d49f"
      MESSAGE_BROKER_URL: "amqp://guest:guest@rabbitmq:5672"
    depends_on:
      - waitforrabbit
      - mongo_db
      - rabbitmq

  #Node users API service
  query:
    build:
      context: ./query
      dockerfile: Dockerfile
    container_name: query
    restart: always
    ports:
      - 4000:4000
    volumes:
      - ./query:/query/src/app/
    env_file: query/.env.dev
    depends_on:
      - waitforrabbit
      - mongo_db
      - rabbitmq

  #Node comments API service
  comments:
    build:
      context: ./comments
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8002:8002
    volumes:
      - ./comments:/comments/src/app/
    env_file: query/.env.dev
    depends_on:
      - waitforrabbit
      - mongo_db
      - rabbitmq

  #Node shares API service
  shares:
    build: 
      context: ./shares
      dockerfile: Dockerfile    
    container_name: shares
    restart: always
    ports:
      - 8002:8002
    volumes:
      - ./shares:/shares/src/app 
    environment:
      APP_SECRET: "barkat"
      MONGODB_URI: "mongodb://mongo_db:27017/shares"
      PORT: 8002
      MOJO_API_KEY: "test-39c833cd-adc0-4787-8027-400b8551d49f"
      MESSAGE_BROKER_URL: "amqp://guest:guest@rabbitmq:5672"  
    depends_on:
      - waitforrabbit
      - mongo_db
      - rabbitmq

volumes:
  mongo_db: {}
