const STATUS_CODES = {
    OK: 200,
    USER_CREATED: 201,
    BAD_REQUEST: 400,
    UN_AUTHORISED: 403,
    NOT_FOUND: 404,
    INTERNAL_ERROR: 500,
    USER_ALREADY_EXIST: 409,
  };

  module.exports = {
    STATUS_CODES,
  };