version: "3.9"

services:
  #MongoDB services
  mongo_db:
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - mongo_db:/data/db

  #Rabbitmq services
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    restart: always
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_nodejs
  #Node API service
  api:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/users/src/app
    environment:
      APP_SECRET: "barkat"
      MONGODB_URI: "mongodb://mongo_db:27017/users"
      PORT: 8000
      MOJO_API_KEY: "test-39c833cd-adc0-4787-8027-400b8551d49f"
      MESSAGE_BROKER_URL: "amqp://guest:guest@rabbitmq:5672"
    depends_on:
      - mongo_db
      - rabbitmq

volumes:
  mongo_db: {}

networks:
  rabbitmq_nodejs:
    driver: bridge
